### ISSUE TITLE
Strange kerning: C and O are too far away

### ISSUE THREAD

**Issue by merwok** [JoebRogers/MadeWithPICO-8Badges#1]
title says all :slightly_smiling_face:

**Comment by JoebRogers** [comment]
Could you provide an image example demonstrating the issue? Device/browser specs would also be nice! There isn't really much I can do about it, as the badges themselves are generated by a tool, but the output has always been stable and consistent for me at least, so I'd be interested to know what's going wrong on your end for this to happen.

Here's what I see from my end:

![chrome_psiyFnZsu6](https://user-images.githubusercontent.com/12448796/69666675-9f10c980-105a-11ea-8edd-55487e431b17.png)

EDIT: Update, after testing on Firefox I believe I see what you're referring to. I'll investigate, as it looks like some odd font issues.

**Comment by JoebRogers** [comment]
Added a section to the readme near the bottom with steps to take for better results. Not a perfect fix by any means, but likely as good as can be done right now.

**Comment by merwok** [comment]
Thanks for looking into this.  I’m using Firefox 68.2.0esr on Debian testing with an X desktop.  The PNG version looks the same to me:

![firefox-example-badge](https://user-images.githubusercontent.com/635179/69676261-5c58ec80-106e-11ea-898d-417dce256709.png)

I’ve tried inspecting the SVG, but devtools don’t show any font information.

**Comment by JoebRogers** [comment]
Yeah, my understanding is that they load dynamic fonts into the SVG (which is why the PNG is at least more consistent for results). My small digging showed they were previously having kerning issues (a long time ago) due to CSS issues with minimum font size and other various inconsistencies from Firefox specifically. 

Unfortunately there's nothing I can actually do to stabilise the results any further than what is already available here. That said, I *do* believe the issue isn't particularly widespread - as whilst I was able to reproduce somewhat of a kerning/font related issue in Firefox when I investigated earlier (at my work computer), Firefox on my home computer displays it perfectly.

**Comment by merwok** [comment]
OK!  I guess I can assume that it will render fine for most people, and if I’m annoyed by my version I can always take the PNG you pasted here, or make my own in PICO-8 :smiley:   Cheers

**Comment by JoebRogers** [comment]
Haha yep, exactly. I may look into other possible avenues in the future, just when I was previously putting these up, Shields.io was the most prevalent for customizable badges. If I get some time, I'll see if there are any alternatives out there that can at least potentially offer better stability on major platforms. Thanks for flagging anyway!

**Comment by JoebRogers** [comment]
@merwok Just updating to let you know that I found an alternative hosting option, which at least operates better on my Firefox. Further details are now listed in the readme, if you'd like to try it out as an alternative!

**Comment by merwok** [comment]
Badgen pictures look better for me too!

**Comment by JoebRogers** [comment]
Good to hear!
